import logging
import os
import re
import smtplib
from email.message import EmailMessage
from langchain_openai import ChatOpenAI
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import (
    ApplicationBuilder, CommandHandler, CallbackQueryHandler,
    MessageHandler, filters, ContextTypes
)
from test_free_text_in_telegram import (
    execute_case_closing,
    check_case_exists,
    generate_individual_case_summary,
    generate_report_for_forms,
    generate_summary_of_all_issues,
    generate_and_execute_sql,
    generate_report_from_prompt,
    execute_case_escalation
)

# Setup logging
logging.basicConfig(
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    level=logging.INFO
)

schema = """
Tables:
- flock_farm_information(id, case_id, type_of_chicken, age_of_chicken, housing_type, number_of_affected_flocks, feed_type, environment_information, timestamp)
- symptoms_performance_data(id, case_id, main_symptoms, daily_production_performance, pattern_of_spread_or_drop, timestamp)
- medical_diagnostic_records(id, case_id, vaccination_history, lab_data, pathology_findings_necropsy, current_treatment, management_questions, timestamp)
- issues(id, title, description, farm_name, status, close_reason, assigned_team, case_id, created_at, updated_at)
- farmer_problem(id, case_id, problem_description, timestamp)
- notifications(id, recipient_team, message, sent_at)
- issue_attachments(id, case_id, file_name, file_path, uploaded_at)
"""

TELEGRAM_BOT_TOKEN = "7020100788:AAHwAgmmocZHULAdthkhzI7vMxbks3G8NVs"
EMAIL_PASSKEY = os.getenv("EMAIL_PASSKEY")
user_state = {}
    
def send_escalation_email(case_id: str, reason: str, case_info: str):
    try:
        msg = EmailMessage()
        msg["Subject"] = f"🚨 Escalation Notice: Case #{case_id}"
        msg["From"] = "2006limjy@gmail.com"
        msg["To"] = "2006limjy@gmail.com"

        msg.set_content(f"""
A case has been escalated by a sales user.

Case ID: {case_id}
Reason for Escalation:
{reason}

Case Details:
{case_info}

Please review and follow up promptly, thank you.
""")
        html_content = f"""
        <html>
            <head>
                <style>
                    body {{
                        font-family: Arial, sans-serif;
                        background-color: #f4f4f9;
                        padding: 20px;
                        color: #333;
                    }}
                    .container {{
                        background-color: #ffffff;
                        padding: 20px;
                        border-radius: 10px;
                        box-shadow: 0 2px 5px rgba(0,0,0,0.1);
                    }}
                    h1 {{
                        color: #d9534f;
                    }}
                    .section-title {{
                        margin-top: 20px;
                        font-size: 18px;
                        color: #e67e22;
                    }}
                    .info-box {{
                        background-color: #f9f9f9;
                        border-left: 5px solid #e67e22;
                        padding: 10px;
                        margin-top: 10px;
                        white-space: pre-wrap;
                    }}
                    .footer {{
                        margin-top: 30px;
                        font-size: 12px;
                        color: #aaa;
                    }}
                </style>
            </head>
            <body>
                <div class="container">
                    <h1 style="margin-bottom: 10px; text-align:center">Technical Escalation Notice</h1>
                    <p><strong>Case ID:</strong> #{case_id}</p>
                    <div class="section-title">Reason for Escalation:</div>
                    <div class="info-box">{reason}</div>

                    <div class="section-title">Case Summary:</div>
                    <div class="info-box">{case_info}</div>

                    <p>Please review and follow up promptly. Thank you.</p>
                    <div class="footer">
                    This email was automatically generated by the Japfa Case Management System.
                    </div>
                </div>
            </body>
        </html>
        """

        msg.add_alternative(html_content, subtype="html")

        # Send email
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
            smtp.login("2006limjy@gmail.com", EMAIL_PASSKEY)
            smtp.send_message(msg)

        return True
    except Exception as e:
        print(f"❌ Error sending email: {e}")
        return False

# Create inline button layout
def get_main_menu_buttons():
    keyboard = [
        [
            InlineKeyboardButton("Get Case Summary", callback_data="case_summary"),
            InlineKeyboardButton("Generate Report", callback_data="generate_report"),
            InlineKeyboardButton("View All Issues", callback_data="view_all_issues")
        ],
        [
            InlineKeyboardButton("Close Case", callback_data="close_case"),
            InlineKeyboardButton("Escalate Case", callback_data="escalate_case")
        ]
    ]
    return InlineKeyboardMarkup(keyboard)

async def show_main_menu(update: Update):
    """Send the main menu to the user."""
    await update.message.reply_text(
        "📋 Main Menu: Please choose an option below:",
        reply_markup=get_main_menu_buttons()
    )

# /start command
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await show_main_menu(update)

# Button interactions
async def button_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    query = update.callback_query
    user_id = query.from_user.id
    await query.answer()

    if query.data == "case_summary":
        user_state[user_id] = {"action": "case_summary", "step": "awaiting_case_id"}
        await query.edit_message_text("📥 Please enter the Case ID for the summary:")

    elif query.data == "generate_report":
        user_state[user_id] = {"action": "generate_report", "step": "awaiting_case_id"}
        await query.edit_message_text("📥 Please enter the Case ID for the full report:")

    elif query.data == "view_all_issues":
        await query.edit_message_text("🔍 Viewing all issues...")
        try:
            result = generate_summary_of_all_issues()
            await query.message.reply_text(f"<pre>{result}</pre>", parse_mode="HTML")
        except Exception as e:
            await query.message.reply_text(f"❌ Error: {e}")

        # Show menu again
        await query.message.reply_text("📋 Main Menu: Please choose an option below:", reply_markup=get_main_menu_buttons())

    elif query.data == "close_case":
        user_state[user_id] = {"action": "closing_case", "step": "awaiting_case_id"}
        await query.edit_message_text("📥 Please enter the Case ID for the case you want to close.")

    elif query.data == "escalate_case":
        user_state[user_id] = {"action": "escalating_case", "step": "awaiting_case_id"}
        await query.edit_message_text("📥 Please enter the Case ID for the case you want to escalate.")

async def case_id_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_id = update.message.from_user.id
    user_input = update.message.text.strip()

    if user_id not in user_state:
        # Try to extract case_id (e.g., "case 12", "case_id=12", "for case: 12")
        case_match = re.search(r"(?:case[_\s]*id)?[^\d]*(\d+)", user_input, re.IGNORECASE)
        case_id = int(case_match.group(1)) if case_match else None

        await update.message.reply_text("🔍 Processing your request...")

        try:
            result = generate_and_execute_sql(schema=schema, user_input=user_input, case_id=case_id)
            report =  generate_report_from_prompt(result)

            if not result:
                await update.message.reply_text("⚠️ No data found or unable to generate query.")
                return
            
            await update.message.reply_text("📝 Here's the report:")
            await update.message.reply_text(f"<pre>{report}</pre>", parse_mode="HTML")

        except Exception as e:
            await update.message.reply_text(f"❌ Error: {e}")

        await show_main_menu(update)
        return

    if user_id not in user_state:
        await update.message.reply_text("❓ Please choose an action first using the menu.")
        await show_main_menu(update)
        return

    state = user_state[user_id]

    # Handle action based on user state
    if state["action"] == "closing_case":
            if state["step"] == "awaiting_case_id":
                if not user_input.isdigit():
                    await update.message.reply_text("❗ Please enter a valid numeric Case ID.")
                    return

                if not check_case_exists(user_input):
                    await update.message.reply_text(f"❌ Case ID {user_input} does not exist, please try again.")
                    return

                state["case_id"] = user_input
                state["step"] = "awaiting_reason"
                await update.message.reply_text(f"📝 Please provide a reason for closing the case {user_input}:")

            elif state["step"] == "awaiting_reason":
                state["reason"] = user_input
                state["step"] = "waiting_for_upload_or_skip"
                await update.message.reply_text(
                    "📤 Upload a document to support your case (optional), or type 'skip' to proceed without a document."
                )

            elif state["step"] == "waiting_for_upload_or_skip":
                if user_input.strip().lower() == "skip":
                    reason = state.get("reason", "No reason provided.")
                    try:
                        result = execute_case_closing(state["case_id"], reason)
                        await update.message.reply_text(f"✅ Case closed successfully: {result}")
                    except Exception as e:
                        await update.message.reply_text(f"❌ Case closure failed: {e}")
                    user_state.pop(user_id, None)
                    await show_main_menu(update)
                else:
                    await update.message.reply_text("❗ Please upload a document or type 'skip' to proceed without one.")

    elif state["action"] == "escalating_case":
        if state["step"] == "awaiting_case_id":
            if not user_input.isdigit():
                await update.message.reply_text("❗ Please enter a valid numeric Case ID.")
                return

            if not check_case_exists(user_input):
                await update.message.reply_text(f"❌ Case ID {user_input} does not exist.")
                return

            state["case_id"] = user_input
            state["step"] = "awaiting_reason"
            await update.message.reply_text(f"📝 Please enter the reason for escalating the case {user_input}:")

        elif state["step"] == "awaiting_reason":
            reason = user_input
            case_id = state["case_id"]

            case_info = generate_individual_case_summary(case_id)
            success = send_escalation_email(case_id, reason, case_info)

            if success:
                execute_case_escalation(case_id)
                await update.message.reply_text(f"✅ Case {state['case_id']} has been escalated and the technical team has been notified.")
            else:
                await update.message.reply_text("❌ Failed to send the escalation email. Please try again later.")

            user_state.pop(user_id)
            await show_main_menu(update)

    elif state["action"] == "case_summary":
        # Handle case summary generation
        await update.message.reply_text("⏳ Generating case summary...")
        case_id = int(user_input)
        result = generate_individual_case_summary(case_id)
        await update.message.reply_text(f"<pre>{result}</pre>", parse_mode="HTML")
        await show_main_menu(update)

    elif state["action"] == "generate_report":
        # Handle full report generation
        await update.message.reply_text("⏳ Generating full report...")
        case_id = int(user_input)
        result = generate_report_for_forms(case_id)
        await update.message.reply_text(f"<pre>{result}</pre>", parse_mode="HTML")
        await show_main_menu(update)

    else:
        await update.message.reply_text("⚠️ Unknown action. Please try again.")
        await show_main_menu(update)

# Log errors
async def error(update: Update, context: ContextTypes.DEFAULT_TYPE):
    logging.error(f"Error occurred: {context.error}")

# Launch bot
def run_telegram_bot():
    app = ApplicationBuilder().token(TELEGRAM_BOT_TOKEN).build()

    app.add_handler(CommandHandler("start", start))
    app.add_handler(CallbackQueryHandler(button_handler))
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, case_id_handler))
    app.add_error_handler(error)

    print("🚀 Bot is running...")
    app.run_polling()

if __name__ == '__main__':
    run_telegram_bot()
